[phases.setup]
nixPkgs = ["nodejs-20_x", "openssl"]
nixOverlays = ["https://github.com/railwayapp/nixpacks/raw/main/overlay.nix"]

[phases.install]
cmds = ["npm install", "npx prisma generate"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
